# K-Nearest Neighbors (KNN) - Theory and Implementation


K-Nearest Neighbors (KNN) is a **supervised machine learning algorithm** used for **classification and regression** problems.

### Theory:
- **Lazy Learner**: KNN doesn't learn a model in training. It stores the training dataset.
- **Distance Metric**: Typically uses Euclidean distance to find the closest neighbors.
- **k value**: The number of nearest neighbors used to make predictions.
- **Majority Voting (for classification)**: Class with the most neighbors among the k nearest is selected.
- **Averaging (for regression)**: Average of the values of the k nearest neighbors.

### When to use:
- When you want a simple model that does not assume any distribution.
- Works best with smaller datasets with fewer dimensions.

### Pros:
- Simple and easy to understand.
- No training phase.

### Cons:
- Slow prediction on large datasets.
- Sensitive to the scale of the data.
- Choice of k and distance metric can significantly impact performance.
    

In [1]:
# Importing libraries
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix


In [2]:
# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split into training and testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


In [3]:
# Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [4]:
# Fitting KNN model
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)


KNeighborsClassifier()

In [5]:
# Predictions and Evaluation
y_pred = knn.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45




### Observations:
- You can experiment with different values of `k` and observe how accuracy changes.
- Feature scaling is crucial for distance-based algorithms like KNN.

### Questions for Students:
1. What does the `n_neighbors` parameter do in KNN?
2. Why is feature scaling important for KNN?
3. Try changing the value of `k` to 3 or 7 and observe the results.
4. Can KNN be used for regression problems? If yes, how?
5. Write a function to compute Euclidean distance manually between two points.
6. What are the advantages of KNN?
7. What are the disadvantages of using KNN on large datasets?
8. Explain how KNN handles multi-class classification.
9. What happens if you do not scale features in KNN?
10. Implement KNN from scratch using only NumPy.
